

package demo.sphinx.helloworld;






import java.io.IOException;
import java.net.URL;

import javax.swing.JOptionPane;

import java.io.*;
import java.sql.*;

import edu.cmu.sphinx.frontend.util.Microphone;
import edu.cmu.sphinx.recognizer.Recognizer;
import edu.cmu.sphinx.result.Result;
import edu.cmu.sphinx.util.props.ConfigurationManager;
import edu.cmu.sphinx.util.props.PropertyException;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import java.awt.Rectangle;
import java.awt.Font;
import javax.swing.JLabel;


/**
 *
 * @author admin
 */
public class First extends javax.swing.JFrame {
	

	private static final long serialVersionUID = 1L;
	/**
     * Creates new form HelloWorld
     */
    public First() {
    	
		getContentPane().setBackground(new Color(51, 0, 153));
		
		setFont(new Font("Aparajita", Font.PLAIN, 15));
		setBounds(new Rectangle(6, 8, 0, 0));
		setForeground(Color.BLUE);
		setAutoRequestFocus(false);
		setBackground(new Color(102, 102, 153));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Vsearch = new javax.swing.JButton();
        Vsearch.setIcon(new ImageIcon("C:\\voice\\voice-search.png"));
        setEntertext(new javax.swing.JTextField());

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Vsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voicesearch(evt);
            }
        });
       
        JButton searchbutton = new JButton("Search Meaning");
        searchbutton.setFont(new Font("Tahoma", Font.BOLD, 18));
        searchbutton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		  
        	    	
        	    	
        	    	
        	    
        		try{
        		    DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
        		    Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","db49","db49");
        		    Statement st = conn.createStatement();
        		    
        		    final String s1=entertext.getText();
        		    
        		    if (s1.equals("")) 
        		    {
        		            JOptionPane.showMessageDialog(null,"Please Enter The Word");
        		            return;
        		            
        		    }
        		    
        		         ResultSet res=null;    
        		      res=st.executeQuery("select count(*) from diction where WORD='"+s1+"'");
        			res.next();
        		        int x;
        			x=res.getInt(1);
        			    
        			if(x==1)
        		                   
        		                    {	
        										
        								new	First().setVisible(false);
        								dispose();
        			
        								Thread thread1 = new Thread() {
        								    public void run() {
        								        Meaning m=new Meaning();
        								        try {
													m.display(s1);
												} catch (SQLException e) {
													// TODO Auto-generated catch block
													e.printStackTrace();
												}
        								    }
        								};

        								Thread thread2 = new Thread() {
        								    public void run() {
        								    	Testplay tts= new Testplay();
                		                		tts.performTts(s1);
        								    	/*FreeTTSHelloWorld tts= new FreeTTSHelloWorld();
                		                		try {
													tts.performTts(s1);
												} catch (SQLException e) {
													// TODO Auto-generated catch block
													e.printStackTrace();
												} */
        								    }
        								};

        								// Start the downloads.
        								thread1.start();
        								thread2.start();

        								// Wait for them both to finish
        								//thread1.join();
        								//thread2.join();

        					       								  
         		                    
        		                      
        		                       
        			
        		                              
        		                    } 
        		                    else 
        		                    {
        		                        JOptionPane.showMessageDialog(null, "NO such word exists OR the word has not been updated in the dictionary");
        		                        this.setVisible(false);
        		                       
        		                        return;
        		                    }
        		                 
        		                
        		      

        		            st.close();
        		            conn.close();
        		}
        		                
        		                

        		    catch(Exception e)
        		    {
        		        System.out.println(e);
        		    }// TODO add your h
        		
        		
        		
        	}
        	
        	

			private void setVisible(boolean b) {
				// TODO Auto-generated method stub
				
			}
        });
        
        JLabel lblVoiceSearch = new JLabel("Voice Search");
        lblVoiceSearch.setForeground(new Color(255, 255, 255));
        lblVoiceSearch.setBackground(new Color(255, 255, 255));
        lblVoiceSearch.setFont(new Font("Times New Roman", Font.BOLD | Font.ITALIC, 18));
        
        JLabel label = new JLabel("");
        label.setIcon(new ImageIcon("C:\\voice\\bkground.jpg"));
        
        JLabel lblNewLabel = new JLabel("");
        
        JButton btnWordList = new JButton("WORD LIST");
        btnWordList.setFont(new Font("Lucida Calligraphy", Font.PLAIN, 20));
        
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(316)
        					.addComponent(lblNewLabel)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(176)
        							.addComponent(lblVoiceSearch)
        							.addGap(38)
        							.addComponent(Vsearch, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE))
        						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(btnWordList, GroupLayout.PREFERRED_SIZE, 437, GroupLayout.PREFERRED_SIZE)
        							.addGap(16)))
        					.addPreferredGap(ComponentPlacement.RELATED))
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(entertext, GroupLayout.PREFERRED_SIZE, 258, GroupLayout.PREFERRED_SIZE)
        					.addGap(117)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(searchbutton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGap(1007))
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addComponent(label, GroupLayout.PREFERRED_SIZE, 1353, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(829, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(label, GroupLayout.PREFERRED_SIZE, 272, GroupLayout.PREFERRED_SIZE)
        			.addGap(127)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(entertext, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        				.addComponent(searchbutton, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(lblVoiceSearch)
        					.addGap(24))
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(Vsearch, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
        					.addGap(15)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(100)
        					.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(75)
        					.addComponent(btnWordList)))
        			.addGap(77))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>

    private void voicesearch(java.awt.event.ActionEvent evt)  {
    	
    	
		    	
		    	
    	
		    	
		    	
		    	
		    	Thread thread3 = new Thread() {
		    		
				    public void run() {
				    	HelloWorld hw=new HelloWorld();
				    	String b=null;
				        String a=hw.sound(b);
						entertext.setText(a);
					
						
				    }
		    		
				  
				};
				thread3.start();
				
				
    	
    	}
    	
    	
    	
    
    

    
    
    
   

    

   
    
   public String getValue() {
	   String s1=entertext.getText();
	    
       return s1;
   }
   
    public static void main(String args[]) {
    
    	
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         * 
         * 
         * 
         * 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelloWorld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelloWorld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelloWorld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelloWorld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new First().setVisible(true);
            }
        });
    }
    public javax.swing.JTextField getEntertext() {
		return entertext;
	}

	public void setEntertext(javax.swing.JTextField entertext) {
		this.entertext = entertext;
		entertext.setText("Enter Word Here");
		entertext.setFont(new Font("Tahoma", Font.PLAIN, 20));
	}
	

	
	// Variables declaration - do not modify
    private javax.swing.JTextField entertext;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton Vsearch;
}









